#define USE_AS_LIBRARY
#include <Renderer/Backend/Common.hpp>
#include <Renderer/Backend/Misc/stb_image.hpp>
#include <Renderer/Backend/Window/Window.hpp>
#include <Renderer/Backend/RHI/RenderBackend.hpp>
#include <Renderer/Backend/RHI/RenderDevice/RenderDevice.hpp>
#include <Renderer/Backend/RHI/Swapchain/Swapchain.hpp>
#include <Renderer/Backend/RHI/Buffers/Buffer.hpp>
#include <Renderer/Backend/RHI/Pipeline/Pipeline.hpp>
#include <Renderer/Backend/RHI/Common/Utils.hpp>
#include <Renderer/Backend/Misc/Color/Color.hpp>
#include <Renderer/Backend/Core/Alignement/Alignement.hpp>
#include <Renderer/Backend/RHI/CommandList/CommandList.hpp>
#include <Renderer/Backend/RHI/ShaderProgram/ShaderProgram.hpp>